import BB from "../aseets/benjamin.jpg";
import CC from "../aseets/willian.jpg";

const tableData = [
  {
    id: 1,
    imageSrc: BB,
    name: "Humayimana ",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 3,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 4,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 4,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 5,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 6,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 7,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 8,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 8,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 9,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 10,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 11,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 12,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 13,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 14,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 15,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 15,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 16,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 17,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 18,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 19,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 20,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 21,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 22,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 23,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 24,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 25,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 1,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 1,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 1,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 1,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 1,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 1,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 1,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 1,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 1,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 1,
    imageSrc: BB,
    name: "John Doe",
    cvLink: "path/to/cv1.pdf",
    timeAvailable: "Full-time",
    experience: "5 years",
    level: "Expert",
    course: "React.js",
    phoneNumber: "123-456-7890",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: CC,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
  {
    id: 2,
    imageSrc: BB,
    name: "Jane Smith",
    cvLink: "path/to/cv2.pdf",
    timeAvailable: "Part-time",
    experience: "3 years",
    level: "Intermediate",
    course: "JavaScript",
    phoneNumber: "987-654-3210",
    email: "jane.smith@email.com",
    viewMoreLink: "https://example.com/teacher2",
    bookNowLink: "https://example.com/book/teacher",
  },
];
export default tableData;
